// ==============================================================
// RTL generated by Vitis HLS - High-Level Synthesis from C, C++ and OpenCL v2021.2 (64-bit)
// Version: 2021.2
// Copyright (C) Copyright 1986-2021 Xilinx, Inc. All Rights Reserved.
// 
// ===========================================================

`timescale 1 ns / 1 ps 

module axil_conv2D0_axil_conv2D0_Pipeline_loop_k1_loop_k2 (
        ap_clk,
        ap_rst,
        ap_start,
        ap_done,
        ap_idle,
        ap_ready,
        acc_V,
        select_ln1072,
        select_ln23,
        weights_address0,
        weights_ce0,
        weights_q0,
        img_in_address0,
        img_in_ce0,
        img_in_q0,
        acc_V_2_out,
        acc_V_2_out_ap_vld
);

parameter    ap_ST_fsm_pp0_stage0 = 1'd1;

input   ap_clk;
input   ap_rst;
input   ap_start;
output   ap_done;
output   ap_idle;
output   ap_ready;
input  [20:0] acc_V;
input  [5:0] select_ln1072;
input  [5:0] select_ln23;
output  [4:0] weights_address0;
output   weights_ce0;
input  [7:0] weights_q0;
output  [11:0] img_in_address0;
output   img_in_ce0;
input  [7:0] img_in_q0;
output  [20:0] acc_V_2_out;
output   acc_V_2_out_ap_vld;

reg ap_idle;
reg weights_ce0;
reg img_in_ce0;
reg acc_V_2_out_ap_vld;

(* fsm_encoding = "none" *) reg   [0:0] ap_CS_fsm;
wire    ap_CS_fsm_pp0_stage0;
wire    ap_enable_reg_pp0_iter0;
reg    ap_enable_reg_pp0_iter1;
reg    ap_enable_reg_pp0_iter2;
reg    ap_enable_reg_pp0_iter3;
reg    ap_enable_reg_pp0_iter4;
reg    ap_enable_reg_pp0_iter5;
reg    ap_idle_pp0;
wire    ap_block_state1_pp0_stage0_iter0;
wire    ap_block_state2_pp0_stage0_iter1;
wire    ap_block_state3_pp0_stage0_iter2;
wire    ap_block_state4_pp0_stage0_iter3;
wire    ap_block_state5_pp0_stage0_iter4;
wire    ap_block_state6_pp0_stage0_iter5;
wire    ap_block_pp0_stage0_subdone;
wire   [0:0] icmp_ln1072_fu_160_p2;
reg    ap_condition_exit_pp0_iter0_stage0;
wire    ap_loop_exit_ready;
reg    ap_ready_int;
wire    ap_block_pp0_stage0_11001;
reg   [0:0] icmp_ln1072_reg_357;
reg   [0:0] icmp_ln1072_reg_357_pp0_iter1_reg;
reg   [0:0] icmp_ln1072_reg_357_pp0_iter2_reg;
reg   [0:0] icmp_ln1072_reg_357_pp0_iter3_reg;
wire   [2:0] select_ln27_fu_184_p3;
reg   [2:0] select_ln27_reg_361;
wire   [2:0] select_ln27_1_fu_198_p3;
reg   [2:0] select_ln27_1_reg_367;
wire   [63:0] zext_ln587_fu_280_p1;
wire    ap_block_pp0_stage0;
wire   [63:0] zext_ln587_1_fu_285_p1;
reg   [20:0] acc_V_1_fu_70;
wire  signed [20:0] grp_fu_309_p3;
reg  signed [20:0] ap_sig_allocacmp_acc_V_1_load_1;
wire    ap_loop_init;
reg   [2:0] kcol_V_fu_74;
wire   [2:0] add_ln885_2_fu_206_p2;
reg   [2:0] ap_sig_allocacmp_kcol_V_load;
reg   [2:0] krow_V_fu_78;
reg   [2:0] ap_sig_allocacmp_krow_V_load;
reg   [4:0] indvar_flatten_fu_82;
wire   [4:0] add_ln1072_fu_166_p2;
reg   [4:0] ap_sig_allocacmp_indvar_flatten_load;
wire    ap_block_pp0_stage0_01001;
wire   [0:0] icmp_ln1072_1_fu_178_p2;
wire   [2:0] add_ln885_fu_192_p2;
wire   [5:0] zext_ln27_1_fu_237_p1;
wire   [3:0] zext_ln27_fu_227_p1;
wire   [3:0] zext_ln70_1_fu_248_p1;
wire   [3:0] add_ln70_fu_251_p2;
wire   [4:0] zext_ln70_2_fu_257_p1;
wire   [4:0] shl_ln70_mid2_fu_230_p3;
wire   [5:0] zext_ln70_fu_245_p1;
wire   [5:0] add_ln27_fu_240_p2;
wire   [5:0] add_ln70_2_fu_267_p2;
wire   [4:0] weight_1d_loc_fu_261_p2;
wire   [11:0] image_1d_loc_fu_272_p3;
wire   [7:0] grp_fu_309_p0;
reg    ap_done_reg;
wire    ap_continue_int;
reg    ap_done_int;
reg    ap_loop_exit_ready_pp0_iter1_reg;
reg    ap_loop_exit_ready_pp0_iter2_reg;
reg    ap_loop_exit_ready_pp0_iter3_reg;
reg    ap_loop_exit_ready_pp0_iter4_reg;
reg   [0:0] ap_NS_fsm;
wire    ap_enable_pp0;
wire    ap_start_int;
wire   [15:0] grp_fu_309_p00;
wire    ap_ce_reg;

// power-on initialization
initial begin
#0 ap_CS_fsm = 1'd1;
#0 ap_enable_reg_pp0_iter1 = 1'b0;
#0 ap_enable_reg_pp0_iter2 = 1'b0;
#0 ap_enable_reg_pp0_iter3 = 1'b0;
#0 ap_enable_reg_pp0_iter4 = 1'b0;
#0 ap_enable_reg_pp0_iter5 = 1'b0;
#0 ap_done_reg = 1'b0;
end

axil_conv2D0_mac_muladd_8ns_8s_21s_21_4_1 #(
    .ID( 1 ),
    .NUM_STAGE( 4 ),
    .din0_WIDTH( 8 ),
    .din1_WIDTH( 8 ),
    .din2_WIDTH( 21 ),
    .dout_WIDTH( 21 ))
mac_muladd_8ns_8s_21s_21_4_1_U1(
    .clk(ap_clk),
    .reset(ap_rst),
    .din0(grp_fu_309_p0),
    .din1(weights_q0),
    .din2(ap_sig_allocacmp_acc_V_1_load_1),
    .ce(1'b1),
    .dout(grp_fu_309_p3)
);

axil_conv2D0_flow_control_loop_pipe_sequential_init flow_control_loop_pipe_sequential_init_U(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .ap_start(ap_start),
    .ap_ready(ap_ready),
    .ap_done(ap_done),
    .ap_start_int(ap_start_int),
    .ap_loop_init(ap_loop_init),
    .ap_ready_int(ap_ready_int),
    .ap_loop_exit_ready(ap_condition_exit_pp0_iter0_stage0),
    .ap_loop_exit_done(ap_done_int),
    .ap_continue_int(ap_continue_int),
    .ap_done_int(ap_done_int)
);

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_CS_fsm <= ap_ST_fsm_pp0_stage0;
    end else begin
        ap_CS_fsm <= ap_NS_fsm;
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_done_reg <= 1'b0;
    end else begin
        if ((ap_continue_int == 1'b1)) begin
            ap_done_reg <= 1'b0;
        end else if (((1'b0 == ap_block_pp0_stage0_subdone) & (ap_loop_exit_ready_pp0_iter4_reg == 1'b1))) begin
            ap_done_reg <= 1'b1;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter1 <= 1'b0;
    end else begin
        if ((1'b1 == ap_condition_exit_pp0_iter0_stage0)) begin
            ap_enable_reg_pp0_iter1 <= 1'b0;
        end else if (((1'b0 == ap_block_pp0_stage0_subdone) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
            ap_enable_reg_pp0_iter1 <= ap_start_int;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter2 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter2 <= ap_enable_reg_pp0_iter1;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter3 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter3 <= ap_enable_reg_pp0_iter2;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter4 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter4 <= ap_enable_reg_pp0_iter3;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter5 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter5 <= ap_enable_reg_pp0_iter4;
        end
    end
end

always @ (posedge ap_clk) begin
    if ((1'b0 == ap_block_pp0_stage0_11001)) begin
        if (((1'b1 == ap_CS_fsm_pp0_stage0) & (ap_loop_init == 1'b1))) begin
            acc_V_1_fu_70 <= acc_V;
        end else if ((ap_enable_reg_pp0_iter5 == 1'b1)) begin
            acc_V_1_fu_70 <= grp_fu_309_p3;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        if (((icmp_ln1072_fu_160_p2 == 1'd0) & (ap_enable_reg_pp0_iter0 == 1'b1))) begin
            indvar_flatten_fu_82 <= add_ln1072_fu_166_p2;
        end else if ((ap_loop_init == 1'b1)) begin
            indvar_flatten_fu_82 <= 5'd0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        if (((icmp_ln1072_fu_160_p2 == 1'd0) & (ap_enable_reg_pp0_iter0 == 1'b1))) begin
            kcol_V_fu_74 <= add_ln885_2_fu_206_p2;
        end else if ((ap_loop_init == 1'b1)) begin
            kcol_V_fu_74 <= 3'd0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        if (((icmp_ln1072_fu_160_p2 == 1'd0) & (ap_enable_reg_pp0_iter0 == 1'b1))) begin
            krow_V_fu_78 <= select_ln27_1_fu_198_p3;
        end else if ((ap_loop_init == 1'b1)) begin
            krow_V_fu_78 <= 3'd0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_loop_exit_ready_pp0_iter1_reg <= ap_loop_exit_ready;
        ap_loop_exit_ready_pp0_iter2_reg <= ap_loop_exit_ready_pp0_iter1_reg;
        icmp_ln1072_reg_357 <= icmp_ln1072_fu_160_p2;
        icmp_ln1072_reg_357_pp0_iter1_reg <= icmp_ln1072_reg_357;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b0 == ap_block_pp0_stage0_11001)) begin
        ap_loop_exit_ready_pp0_iter3_reg <= ap_loop_exit_ready_pp0_iter2_reg;
        ap_loop_exit_ready_pp0_iter4_reg <= ap_loop_exit_ready_pp0_iter3_reg;
        icmp_ln1072_reg_357_pp0_iter2_reg <= icmp_ln1072_reg_357_pp0_iter1_reg;
        icmp_ln1072_reg_357_pp0_iter3_reg <= icmp_ln1072_reg_357_pp0_iter2_reg;
    end
end

always @ (posedge ap_clk) begin
    if (((icmp_ln1072_fu_160_p2 == 1'd0) & (1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        select_ln27_1_reg_367 <= select_ln27_1_fu_198_p3;
        select_ln27_reg_361 <= select_ln27_fu_184_p3;
    end
end

always @ (*) begin
    if (((icmp_ln1072_reg_357_pp0_iter3_reg == 1'd1) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        acc_V_2_out_ap_vld = 1'b1;
    end else begin
        acc_V_2_out_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((icmp_ln1072_fu_160_p2 == 1'd1) & (1'b0 == ap_block_pp0_stage0_subdone) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_condition_exit_pp0_iter0_stage0 = 1'b1;
    end else begin
        ap_condition_exit_pp0_iter0_stage0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_subdone) & (ap_loop_exit_ready_pp0_iter4_reg == 1'b1))) begin
        ap_done_int = 1'b1;
    end else begin
        ap_done_int = ap_done_reg;
    end
end

always @ (*) begin
    if (((ap_idle_pp0 == 1'b1) & (ap_start_int == 1'b0) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_idle = 1'b1;
    end else begin
        ap_idle = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter5 == 1'b0) & (ap_enable_reg_pp0_iter4 == 1'b0) & (ap_enable_reg_pp0_iter3 == 1'b0) & (ap_enable_reg_pp0_iter2 == 1'b0) & (ap_enable_reg_pp0_iter1 == 1'b0) & (ap_enable_reg_pp0_iter0 == 1'b0))) begin
        ap_idle_pp0 = 1'b1;
    end else begin
        ap_idle_pp0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_subdone) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_ready_int = 1'b1;
    end else begin
        ap_ready_int = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0) & (ap_enable_reg_pp0_iter5 == 1'b1))) begin
        ap_sig_allocacmp_acc_V_1_load_1 = grp_fu_309_p3;
    end else begin
        ap_sig_allocacmp_acc_V_1_load_1 = acc_V_1_fu_70;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0) & (1'b1 == ap_CS_fsm_pp0_stage0) & (ap_loop_init == 1'b1))) begin
        ap_sig_allocacmp_indvar_flatten_load = 5'd0;
    end else begin
        ap_sig_allocacmp_indvar_flatten_load = indvar_flatten_fu_82;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0) & (1'b1 == ap_CS_fsm_pp0_stage0) & (ap_loop_init == 1'b1))) begin
        ap_sig_allocacmp_kcol_V_load = 3'd0;
    end else begin
        ap_sig_allocacmp_kcol_V_load = kcol_V_fu_74;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0) & (1'b1 == ap_CS_fsm_pp0_stage0) & (ap_loop_init == 1'b1))) begin
        ap_sig_allocacmp_krow_V_load = 3'd0;
    end else begin
        ap_sig_allocacmp_krow_V_load = krow_V_fu_78;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        img_in_ce0 = 1'b1;
    end else begin
        img_in_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        weights_ce0 = 1'b1;
    end else begin
        weights_ce0 = 1'b0;
    end
end

always @ (*) begin
    case (ap_CS_fsm)
        ap_ST_fsm_pp0_stage0 : begin
            ap_NS_fsm = ap_ST_fsm_pp0_stage0;
        end
        default : begin
            ap_NS_fsm = 'bx;
        end
    endcase
end

assign acc_V_2_out = acc_V_1_fu_70;

assign add_ln1072_fu_166_p2 = (ap_sig_allocacmp_indvar_flatten_load + 5'd1);

assign add_ln27_fu_240_p2 = (zext_ln27_1_fu_237_p1 + select_ln1072);

assign add_ln70_2_fu_267_p2 = (select_ln23 + zext_ln70_fu_245_p1);

assign add_ln70_fu_251_p2 = (zext_ln27_fu_227_p1 + zext_ln70_1_fu_248_p1);

assign add_ln885_2_fu_206_p2 = (select_ln27_fu_184_p3 + 3'd1);

assign add_ln885_fu_192_p2 = (ap_sig_allocacmp_krow_V_load + 3'd1);

assign ap_CS_fsm_pp0_stage0 = ap_CS_fsm[32'd0];

assign ap_block_pp0_stage0 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage0_01001 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage0_11001 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage0_subdone = ~(1'b1 == 1'b1);

assign ap_block_state1_pp0_stage0_iter0 = ~(1'b1 == 1'b1);

assign ap_block_state2_pp0_stage0_iter1 = ~(1'b1 == 1'b1);

assign ap_block_state3_pp0_stage0_iter2 = ~(1'b1 == 1'b1);

assign ap_block_state4_pp0_stage0_iter3 = ~(1'b1 == 1'b1);

assign ap_block_state5_pp0_stage0_iter4 = ~(1'b1 == 1'b1);

assign ap_block_state6_pp0_stage0_iter5 = ~(1'b1 == 1'b1);

assign ap_enable_pp0 = (ap_idle_pp0 ^ 1'b1);

assign ap_enable_reg_pp0_iter0 = ap_start_int;

assign ap_loop_exit_ready = ap_condition_exit_pp0_iter0_stage0;

assign grp_fu_309_p0 = grp_fu_309_p00;

assign grp_fu_309_p00 = img_in_q0;

assign icmp_ln1072_1_fu_178_p2 = ((ap_sig_allocacmp_kcol_V_load == 3'd5) ? 1'b1 : 1'b0);

assign icmp_ln1072_fu_160_p2 = ((ap_sig_allocacmp_indvar_flatten_load == 5'd25) ? 1'b1 : 1'b0);

assign image_1d_loc_fu_272_p3 = {{add_ln27_fu_240_p2}, {add_ln70_2_fu_267_p2}};

assign img_in_address0 = zext_ln587_1_fu_285_p1;

assign select_ln27_1_fu_198_p3 = ((icmp_ln1072_1_fu_178_p2[0:0] == 1'b1) ? add_ln885_fu_192_p2 : ap_sig_allocacmp_krow_V_load);

assign select_ln27_fu_184_p3 = ((icmp_ln1072_1_fu_178_p2[0:0] == 1'b1) ? 3'd0 : ap_sig_allocacmp_kcol_V_load);

assign shl_ln70_mid2_fu_230_p3 = {{select_ln27_1_reg_367}, {2'd0}};

assign weight_1d_loc_fu_261_p2 = (zext_ln70_2_fu_257_p1 + shl_ln70_mid2_fu_230_p3);

assign weights_address0 = zext_ln587_fu_280_p1;

assign zext_ln27_1_fu_237_p1 = select_ln27_1_reg_367;

assign zext_ln27_fu_227_p1 = select_ln27_1_reg_367;

assign zext_ln587_1_fu_285_p1 = image_1d_loc_fu_272_p3;

assign zext_ln587_fu_280_p1 = weight_1d_loc_fu_261_p2;

assign zext_ln70_1_fu_248_p1 = select_ln27_reg_361;

assign zext_ln70_2_fu_257_p1 = add_ln70_fu_251_p2;

assign zext_ln70_fu_245_p1 = select_ln27_reg_361;

endmodule //axil_conv2D0_axil_conv2D0_Pipeline_loop_k1_loop_k2
