
/*******************************************************************
*
* CAUTION: This file is automatically generated by HSI.
* Version: 2021.2
* DO NOT EDIT.
*
* Copyright (C) 2010-2022 Xilinx, Inc. All Rights Reserved.
* SPDX-License-Identifier: MIT 

* 
* Description: Driver configuration
*
*******************************************************************/

#include "xparameters.h"
#include "xaxil_conv2d0.h"

/*
* The configuration table for devices
*/

XAxil_conv2d0_Config XAxil_conv2d0_ConfigTable[XPAR_XAXIL_CONV2D0_NUM_INSTANCES] =
{
	{
		XPAR_AXIL_CONV2D0_0_DEVICE_ID,
		XPAR_AXIL_CONV2D0_0_S_AXI_BUS1_BASEADDR
	}
};


