-- ==============================================================
-- RTL generated by Vitis HLS - High-Level Synthesis from C, C++ and OpenCL v2021.2 (64-bit)
-- Version: 2021.2
-- Copyright (C) Copyright 1986-2021 Xilinx, Inc. All Rights Reserved.
-- 
-- ===========================================================

library IEEE;
use IEEE.std_logic_1164.all;
use IEEE.numeric_std.all;

entity axil_conv2D0_axil_conv2D0_Pipeline_loop_k1_loop_k2 is
port (
    ap_clk : IN STD_LOGIC;
    ap_rst : IN STD_LOGIC;
    ap_start : IN STD_LOGIC;
    ap_done : OUT STD_LOGIC;
    ap_idle : OUT STD_LOGIC;
    ap_ready : OUT STD_LOGIC;
    acc_V : IN STD_LOGIC_VECTOR (20 downto 0);
    zext_ln23 : IN STD_LOGIC_VECTOR (1 downto 0);
    zext_ln27 : IN STD_LOGIC_VECTOR (1 downto 0);
    weights_address0 : OUT STD_LOGIC_VECTOR (3 downto 0);
    weights_ce0 : OUT STD_LOGIC;
    weights_q0 : IN STD_LOGIC_VECTOR (7 downto 0);
    img_in_address0 : OUT STD_LOGIC_VECTOR (5 downto 0);
    img_in_ce0 : OUT STD_LOGIC;
    img_in_q0 : IN STD_LOGIC_VECTOR (7 downto 0);
    acc_V_2_out : OUT STD_LOGIC_VECTOR (20 downto 0);
    acc_V_2_out_ap_vld : OUT STD_LOGIC );
end;


architecture behav of axil_conv2D0_axil_conv2D0_Pipeline_loop_k1_loop_k2 is 
    constant ap_const_logic_1 : STD_LOGIC := '1';
    constant ap_const_logic_0 : STD_LOGIC := '0';
    constant ap_ST_fsm_pp0_stage0 : STD_LOGIC_VECTOR (0 downto 0) := "1";
    constant ap_const_lv32_0 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000000";
    constant ap_const_boolean_1 : BOOLEAN := true;
    constant ap_const_boolean_0 : BOOLEAN := false;
    constant ap_const_lv1_1 : STD_LOGIC_VECTOR (0 downto 0) := "1";
    constant ap_const_lv1_0 : STD_LOGIC_VECTOR (0 downto 0) := "0";
    constant ap_const_lv2_0 : STD_LOGIC_VECTOR (1 downto 0) := "00";
    constant ap_const_lv4_0 : STD_LOGIC_VECTOR (3 downto 0) := "0000";
    constant ap_const_lv3_0 : STD_LOGIC_VECTOR (2 downto 0) := "000";
    constant ap_const_lv4_9 : STD_LOGIC_VECTOR (3 downto 0) := "1001";
    constant ap_const_lv4_1 : STD_LOGIC_VECTOR (3 downto 0) := "0001";
    constant ap_const_lv2_3 : STD_LOGIC_VECTOR (1 downto 0) := "11";
    constant ap_const_lv2_1 : STD_LOGIC_VECTOR (1 downto 0) := "01";

attribute shreg_extract : string;
    signal ap_CS_fsm : STD_LOGIC_VECTOR (0 downto 0) := "1";
    attribute fsm_encoding : string;
    attribute fsm_encoding of ap_CS_fsm : signal is "none";
    signal ap_CS_fsm_pp0_stage0 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_pp0_stage0 : signal is "none";
    signal ap_enable_reg_pp0_iter0 : STD_LOGIC;
    signal ap_enable_reg_pp0_iter1 : STD_LOGIC := '0';
    signal ap_enable_reg_pp0_iter2 : STD_LOGIC := '0';
    signal ap_enable_reg_pp0_iter3 : STD_LOGIC := '0';
    signal ap_enable_reg_pp0_iter4 : STD_LOGIC := '0';
    signal ap_enable_reg_pp0_iter5 : STD_LOGIC := '0';
    signal ap_idle_pp0 : STD_LOGIC;
    signal ap_block_state1_pp0_stage0_iter0 : BOOLEAN;
    signal ap_block_state2_pp0_stage0_iter1 : BOOLEAN;
    signal ap_block_state3_pp0_stage0_iter2 : BOOLEAN;
    signal ap_block_state4_pp0_stage0_iter3 : BOOLEAN;
    signal ap_block_state5_pp0_stage0_iter4 : BOOLEAN;
    signal ap_block_state6_pp0_stage0_iter5 : BOOLEAN;
    signal ap_block_pp0_stage0_subdone : BOOLEAN;
    signal icmp_ln1072_fu_229_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal ap_condition_exit_pp0_iter0_stage0 : STD_LOGIC;
    signal ap_loop_exit_ready : STD_LOGIC;
    signal ap_ready_int : STD_LOGIC;
    signal ap_block_pp0_stage0_11001 : BOOLEAN;
    signal icmp_ln1072_reg_458 : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln1072_reg_458_pp0_iter1_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln1072_reg_458_pp0_iter2_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln1072_reg_458_pp0_iter3_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal weight_1d_loc_fu_350_p2 : STD_LOGIC_VECTOR (3 downto 0);
    signal weight_1d_loc_reg_462 : STD_LOGIC_VECTOR (3 downto 0);
    signal image_1d_loc_fu_366_p2 : STD_LOGIC_VECTOR (5 downto 0);
    signal image_1d_loc_reg_467 : STD_LOGIC_VECTOR (5 downto 0);
    signal zext_ln587_fu_393_p1 : STD_LOGIC_VECTOR (63 downto 0);
    signal ap_block_pp0_stage0 : BOOLEAN;
    signal zext_ln587_1_fu_397_p1 : STD_LOGIC_VECTOR (63 downto 0);
    signal acc_V_1_fu_74 : STD_LOGIC_VECTOR (20 downto 0);
    signal grp_fu_420_p3 : STD_LOGIC_VECTOR (20 downto 0);
    signal ap_sig_allocacmp_acc_V_1_load_1 : STD_LOGIC_VECTOR (20 downto 0);
    signal ap_loop_init : STD_LOGIC;
    signal kcol_V_fu_78 : STD_LOGIC_VECTOR (1 downto 0);
    signal add_ln885_2_fu_372_p2 : STD_LOGIC_VECTOR (1 downto 0);
    signal ap_sig_allocacmp_kcol_V_load : STD_LOGIC_VECTOR (1 downto 0);
    signal krow_V_fu_82 : STD_LOGIC_VECTOR (1 downto 0);
    signal select_ln1072_fu_334_p3 : STD_LOGIC_VECTOR (1 downto 0);
    signal ap_sig_allocacmp_krow_V_1 : STD_LOGIC_VECTOR (1 downto 0);
    signal indvar_flatten_fu_86 : STD_LOGIC_VECTOR (3 downto 0);
    signal add_ln1072_fu_235_p2 : STD_LOGIC_VECTOR (3 downto 0);
    signal ap_sig_allocacmp_indvar_flatten_load : STD_LOGIC_VECTOR (3 downto 0);
    signal ap_block_pp0_stage0_01001 : BOOLEAN;
    signal shl_ln_fu_183_p3 : STD_LOGIC_VECTOR (3 downto 0);
    signal zext_ln70_1_fu_179_p1 : STD_LOGIC_VECTOR (3 downto 0);
    signal zext_ln70_fu_175_p1 : STD_LOGIC_VECTOR (2 downto 0);
    signal zext_ln23_cast_fu_145_p1 : STD_LOGIC_VECTOR (2 downto 0);
    signal add_ln70_fu_197_p2 : STD_LOGIC_VECTOR (2 downto 0);
    signal shl_ln70_2_fu_211_p3 : STD_LOGIC_VECTOR (3 downto 0);
    signal shl_ln70_1_fu_203_p3 : STD_LOGIC_VECTOR (5 downto 0);
    signal zext_ln70_2_fu_219_p1 : STD_LOGIC_VECTOR (5 downto 0);
    signal icmp_ln1072_1_fu_244_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal add_ln885_fu_258_p2 : STD_LOGIC_VECTOR (1 downto 0);
    signal shl_ln70_mid1_fu_272_p3 : STD_LOGIC_VECTOR (3 downto 0);
    signal zext_ln70_4_fu_268_p1 : STD_LOGIC_VECTOR (3 downto 0);
    signal sub_ln70_2_fu_280_p2 : STD_LOGIC_VECTOR (3 downto 0);
    signal sub_ln70_fu_191_p2 : STD_LOGIC_VECTOR (3 downto 0);
    signal zext_ln70_3_fu_264_p1 : STD_LOGIC_VECTOR (2 downto 0);
    signal add_ln70_1_fu_294_p2 : STD_LOGIC_VECTOR (2 downto 0);
    signal shl_ln70_2_mid1_fu_308_p3 : STD_LOGIC_VECTOR (3 downto 0);
    signal shl_ln70_1_mid1_fu_300_p3 : STD_LOGIC_VECTOR (5 downto 0);
    signal zext_ln70_8_fu_316_p1 : STD_LOGIC_VECTOR (5 downto 0);
    signal sub_ln70_3_fu_320_p2 : STD_LOGIC_VECTOR (5 downto 0);
    signal sub_ln70_1_fu_223_p2 : STD_LOGIC_VECTOR (5 downto 0);
    signal select_ln27_fu_250_p3 : STD_LOGIC_VECTOR (1 downto 0);
    signal zext_ln70_6_fu_346_p1 : STD_LOGIC_VECTOR (3 downto 0);
    signal select_ln27_1_fu_286_p3 : STD_LOGIC_VECTOR (3 downto 0);
    signal zext_ln27_cast_fu_141_p1 : STD_LOGIC_VECTOR (2 downto 0);
    signal zext_ln70_5_fu_342_p1 : STD_LOGIC_VECTOR (2 downto 0);
    signal add_ln70_2_fu_356_p2 : STD_LOGIC_VECTOR (2 downto 0);
    signal zext_ln70_7_fu_362_p1 : STD_LOGIC_VECTOR (5 downto 0);
    signal select_ln27_2_fu_326_p3 : STD_LOGIC_VECTOR (5 downto 0);
    signal grp_fu_420_p0 : STD_LOGIC_VECTOR (7 downto 0);
    signal ap_done_reg : STD_LOGIC := '0';
    signal ap_continue_int : STD_LOGIC;
    signal ap_done_int : STD_LOGIC;
    signal ap_loop_exit_ready_pp0_iter1_reg : STD_LOGIC;
    signal ap_loop_exit_ready_pp0_iter2_reg : STD_LOGIC;
    signal ap_loop_exit_ready_pp0_iter3_reg : STD_LOGIC;
    signal ap_loop_exit_ready_pp0_iter4_reg : STD_LOGIC;
    signal ap_NS_fsm : STD_LOGIC_VECTOR (0 downto 0);
    signal ap_enable_pp0 : STD_LOGIC;
    signal ap_start_int : STD_LOGIC;
    signal grp_fu_420_p00 : STD_LOGIC_VECTOR (15 downto 0);
    signal ap_ce_reg : STD_LOGIC;

    component axil_conv2D0_mac_muladd_8ns_8s_21s_21_4_1 IS
    generic (
        ID : INTEGER;
        NUM_STAGE : INTEGER;
        din0_WIDTH : INTEGER;
        din1_WIDTH : INTEGER;
        din2_WIDTH : INTEGER;
        dout_WIDTH : INTEGER );
    port (
        clk : IN STD_LOGIC;
        reset : IN STD_LOGIC;
        din0 : IN STD_LOGIC_VECTOR (7 downto 0);
        din1 : IN STD_LOGIC_VECTOR (7 downto 0);
        din2 : IN STD_LOGIC_VECTOR (20 downto 0);
        ce : IN STD_LOGIC;
        dout : OUT STD_LOGIC_VECTOR (20 downto 0) );
    end component;


    component axil_conv2D0_flow_control_loop_pipe_sequential_init IS
    port (
        ap_clk : IN STD_LOGIC;
        ap_rst : IN STD_LOGIC;
        ap_start : IN STD_LOGIC;
        ap_ready : OUT STD_LOGIC;
        ap_done : OUT STD_LOGIC;
        ap_start_int : OUT STD_LOGIC;
        ap_loop_init : OUT STD_LOGIC;
        ap_ready_int : IN STD_LOGIC;
        ap_loop_exit_ready : IN STD_LOGIC;
        ap_loop_exit_done : IN STD_LOGIC;
        ap_continue_int : OUT STD_LOGIC;
        ap_done_int : IN STD_LOGIC );
    end component;



begin
    mac_muladd_8ns_8s_21s_21_4_1_U1 : component axil_conv2D0_mac_muladd_8ns_8s_21s_21_4_1
    generic map (
        ID => 1,
        NUM_STAGE => 4,
        din0_WIDTH => 8,
        din1_WIDTH => 8,
        din2_WIDTH => 21,
        dout_WIDTH => 21)
    port map (
        clk => ap_clk,
        reset => ap_rst,
        din0 => grp_fu_420_p0,
        din1 => weights_q0,
        din2 => ap_sig_allocacmp_acc_V_1_load_1,
        ce => ap_const_logic_1,
        dout => grp_fu_420_p3);

    flow_control_loop_pipe_sequential_init_U : component axil_conv2D0_flow_control_loop_pipe_sequential_init
    port map (
        ap_clk => ap_clk,
        ap_rst => ap_rst,
        ap_start => ap_start,
        ap_ready => ap_ready,
        ap_done => ap_done,
        ap_start_int => ap_start_int,
        ap_loop_init => ap_loop_init,
        ap_ready_int => ap_ready_int,
        ap_loop_exit_ready => ap_condition_exit_pp0_iter0_stage0,
        ap_loop_exit_done => ap_done_int,
        ap_continue_int => ap_continue_int,
        ap_done_int => ap_done_int);





    ap_CS_fsm_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_CS_fsm <= ap_ST_fsm_pp0_stage0;
            else
                ap_CS_fsm <= ap_NS_fsm;
            end if;
        end if;
    end process;


    ap_done_reg_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_done_reg <= ap_const_logic_0;
            else
                if ((ap_continue_int = ap_const_logic_1)) then 
                    ap_done_reg <= ap_const_logic_0;
                elsif (((ap_const_boolean_0 = ap_block_pp0_stage0_subdone) and (ap_loop_exit_ready_pp0_iter4_reg = ap_const_logic_1))) then 
                    ap_done_reg <= ap_const_logic_1;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter1_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp0_iter1 <= ap_const_logic_0;
            else
                if ((ap_const_logic_1 = ap_condition_exit_pp0_iter0_stage0)) then 
                    ap_enable_reg_pp0_iter1 <= ap_const_logic_0;
                elsif (((ap_const_boolean_0 = ap_block_pp0_stage0_subdone) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
                    ap_enable_reg_pp0_iter1 <= ap_start_int;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter2_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp0_iter2 <= ap_const_logic_0;
            else
                if ((ap_const_boolean_0 = ap_block_pp0_stage0_subdone)) then 
                    ap_enable_reg_pp0_iter2 <= ap_enable_reg_pp0_iter1;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter3_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp0_iter3 <= ap_const_logic_0;
            else
                if ((ap_const_boolean_0 = ap_block_pp0_stage0_subdone)) then 
                    ap_enable_reg_pp0_iter3 <= ap_enable_reg_pp0_iter2;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter4_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp0_iter4 <= ap_const_logic_0;
            else
                if ((ap_const_boolean_0 = ap_block_pp0_stage0_subdone)) then 
                    ap_enable_reg_pp0_iter4 <= ap_enable_reg_pp0_iter3;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter5_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp0_iter5 <= ap_const_logic_0;
            else
                if ((ap_const_boolean_0 = ap_block_pp0_stage0_subdone)) then 
                    ap_enable_reg_pp0_iter5 <= ap_enable_reg_pp0_iter4;
                end if; 
            end if;
        end if;
    end process;


    acc_V_1_fu_74_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_boolean_0 = ap_block_pp0_stage0_11001)) then
                if (((ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (ap_loop_init = ap_const_logic_1))) then 
                    acc_V_1_fu_74 <= acc_V;
                elsif ((ap_enable_reg_pp0_iter5 = ap_const_logic_1)) then 
                    acc_V_1_fu_74 <= grp_fu_420_p3;
                end if;
            end if; 
        end if;
    end process;

    indvar_flatten_fu_86_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then
                if (((icmp_ln1072_fu_229_p2 = ap_const_lv1_0) and (ap_enable_reg_pp0_iter0 = ap_const_logic_1))) then 
                    indvar_flatten_fu_86 <= add_ln1072_fu_235_p2;
                elsif ((ap_loop_init = ap_const_logic_1)) then 
                    indvar_flatten_fu_86 <= ap_const_lv4_0;
                end if;
            end if; 
        end if;
    end process;

    kcol_V_fu_78_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then
                if (((icmp_ln1072_fu_229_p2 = ap_const_lv1_0) and (ap_enable_reg_pp0_iter0 = ap_const_logic_1))) then 
                    kcol_V_fu_78 <= add_ln885_2_fu_372_p2;
                elsif ((ap_loop_init = ap_const_logic_1)) then 
                    kcol_V_fu_78 <= ap_const_lv2_0;
                end if;
            end if; 
        end if;
    end process;

    krow_V_fu_82_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then
                if (((icmp_ln1072_fu_229_p2 = ap_const_lv1_0) and (ap_enable_reg_pp0_iter0 = ap_const_logic_1))) then 
                    krow_V_fu_82 <= select_ln1072_fu_334_p3;
                elsif ((ap_loop_init = ap_const_logic_1)) then 
                    krow_V_fu_82 <= ap_const_lv2_0;
                end if;
            end if; 
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then
                ap_loop_exit_ready_pp0_iter1_reg <= ap_loop_exit_ready;
                ap_loop_exit_ready_pp0_iter2_reg <= ap_loop_exit_ready_pp0_iter1_reg;
                icmp_ln1072_reg_458 <= icmp_ln1072_fu_229_p2;
                icmp_ln1072_reg_458_pp0_iter1_reg <= icmp_ln1072_reg_458;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_boolean_0 = ap_block_pp0_stage0_11001)) then
                ap_loop_exit_ready_pp0_iter3_reg <= ap_loop_exit_ready_pp0_iter2_reg;
                ap_loop_exit_ready_pp0_iter4_reg <= ap_loop_exit_ready_pp0_iter3_reg;
                icmp_ln1072_reg_458_pp0_iter2_reg <= icmp_ln1072_reg_458_pp0_iter1_reg;
                icmp_ln1072_reg_458_pp0_iter3_reg <= icmp_ln1072_reg_458_pp0_iter2_reg;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((icmp_ln1072_fu_229_p2 = ap_const_lv1_0) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then
                image_1d_loc_reg_467 <= image_1d_loc_fu_366_p2;
                weight_1d_loc_reg_462 <= weight_1d_loc_fu_350_p2;
            end if;
        end if;
    end process;

    ap_NS_fsm_assign_proc : process (ap_CS_fsm)
    begin
        case ap_CS_fsm is
            when ap_ST_fsm_pp0_stage0 => 
                ap_NS_fsm <= ap_ST_fsm_pp0_stage0;
            when others =>  
                ap_NS_fsm <= "X";
        end case;
    end process;
    acc_V_2_out <= acc_V_1_fu_74;

    acc_V_2_out_ap_vld_assign_proc : process(ap_block_pp0_stage0_11001, icmp_ln1072_reg_458_pp0_iter3_reg)
    begin
        if (((icmp_ln1072_reg_458_pp0_iter3_reg = ap_const_lv1_1) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001))) then 
            acc_V_2_out_ap_vld <= ap_const_logic_1;
        else 
            acc_V_2_out_ap_vld <= ap_const_logic_0;
        end if; 
    end process;

    add_ln1072_fu_235_p2 <= std_logic_vector(unsigned(ap_sig_allocacmp_indvar_flatten_load) + unsigned(ap_const_lv4_1));
    add_ln70_1_fu_294_p2 <= std_logic_vector(unsigned(zext_ln70_3_fu_264_p1) + unsigned(zext_ln23_cast_fu_145_p1));
    add_ln70_2_fu_356_p2 <= std_logic_vector(unsigned(zext_ln27_cast_fu_141_p1) + unsigned(zext_ln70_5_fu_342_p1));
    add_ln70_fu_197_p2 <= std_logic_vector(unsigned(zext_ln70_fu_175_p1) + unsigned(zext_ln23_cast_fu_145_p1));
    add_ln885_2_fu_372_p2 <= std_logic_vector(unsigned(select_ln27_fu_250_p3) + unsigned(ap_const_lv2_1));
    add_ln885_fu_258_p2 <= std_logic_vector(unsigned(ap_sig_allocacmp_krow_V_1) + unsigned(ap_const_lv2_1));
    ap_CS_fsm_pp0_stage0 <= ap_CS_fsm(0);
        ap_block_pp0_stage0 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_pp0_stage0_01001 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_pp0_stage0_11001 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_pp0_stage0_subdone <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_state1_pp0_stage0_iter0 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_state2_pp0_stage0_iter1 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_state3_pp0_stage0_iter2 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_state4_pp0_stage0_iter3 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_state5_pp0_stage0_iter4 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_state6_pp0_stage0_iter5 <= not((ap_const_boolean_1 = ap_const_boolean_1));

    ap_condition_exit_pp0_iter0_stage0_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter0, ap_block_pp0_stage0_subdone, icmp_ln1072_fu_229_p2)
    begin
        if (((icmp_ln1072_fu_229_p2 = ap_const_lv1_1) and (ap_const_boolean_0 = ap_block_pp0_stage0_subdone) and (ap_enable_reg_pp0_iter0 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            ap_condition_exit_pp0_iter0_stage0 <= ap_const_logic_1;
        else 
            ap_condition_exit_pp0_iter0_stage0 <= ap_const_logic_0;
        end if; 
    end process;


    ap_done_int_assign_proc : process(ap_block_pp0_stage0_subdone, ap_done_reg, ap_loop_exit_ready_pp0_iter4_reg)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_subdone) and (ap_loop_exit_ready_pp0_iter4_reg = ap_const_logic_1))) then 
            ap_done_int <= ap_const_logic_1;
        else 
            ap_done_int <= ap_done_reg;
        end if; 
    end process;

    ap_enable_pp0 <= (ap_idle_pp0 xor ap_const_logic_1);
    ap_enable_reg_pp0_iter0 <= ap_start_int;

    ap_idle_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_idle_pp0, ap_start_int)
    begin
        if (((ap_idle_pp0 = ap_const_logic_1) and (ap_start_int = ap_const_logic_0) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            ap_idle <= ap_const_logic_1;
        else 
            ap_idle <= ap_const_logic_0;
        end if; 
    end process;


    ap_idle_pp0_assign_proc : process(ap_enable_reg_pp0_iter0, ap_enable_reg_pp0_iter1, ap_enable_reg_pp0_iter2, ap_enable_reg_pp0_iter3, ap_enable_reg_pp0_iter4, ap_enable_reg_pp0_iter5)
    begin
        if (((ap_enable_reg_pp0_iter5 = ap_const_logic_0) and (ap_enable_reg_pp0_iter4 = ap_const_logic_0) and (ap_enable_reg_pp0_iter3 = ap_const_logic_0) and (ap_enable_reg_pp0_iter2 = ap_const_logic_0) and (ap_enable_reg_pp0_iter1 = ap_const_logic_0) and (ap_enable_reg_pp0_iter0 = ap_const_logic_0))) then 
            ap_idle_pp0 <= ap_const_logic_1;
        else 
            ap_idle_pp0 <= ap_const_logic_0;
        end if; 
    end process;

    ap_loop_exit_ready <= ap_condition_exit_pp0_iter0_stage0;

    ap_ready_int_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter0, ap_block_pp0_stage0_subdone)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_subdone) and (ap_enable_reg_pp0_iter0 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            ap_ready_int <= ap_const_logic_1;
        else 
            ap_ready_int <= ap_const_logic_0;
        end if; 
    end process;


    ap_sig_allocacmp_acc_V_1_load_1_assign_proc : process(ap_enable_reg_pp0_iter5, ap_block_pp0_stage0, acc_V_1_fu_74, grp_fu_420_p3)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0) and (ap_enable_reg_pp0_iter5 = ap_const_logic_1))) then 
            ap_sig_allocacmp_acc_V_1_load_1 <= grp_fu_420_p3;
        else 
            ap_sig_allocacmp_acc_V_1_load_1 <= acc_V_1_fu_74;
        end if; 
    end process;


    ap_sig_allocacmp_indvar_flatten_load_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_block_pp0_stage0, ap_loop_init, indvar_flatten_fu_86)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (ap_loop_init = ap_const_logic_1))) then 
            ap_sig_allocacmp_indvar_flatten_load <= ap_const_lv4_0;
        else 
            ap_sig_allocacmp_indvar_flatten_load <= indvar_flatten_fu_86;
        end if; 
    end process;


    ap_sig_allocacmp_kcol_V_load_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_block_pp0_stage0, ap_loop_init, kcol_V_fu_78)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (ap_loop_init = ap_const_logic_1))) then 
            ap_sig_allocacmp_kcol_V_load <= ap_const_lv2_0;
        else 
            ap_sig_allocacmp_kcol_V_load <= kcol_V_fu_78;
        end if; 
    end process;


    ap_sig_allocacmp_krow_V_1_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_block_pp0_stage0, ap_loop_init, krow_V_fu_82)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (ap_loop_init = ap_const_logic_1))) then 
            ap_sig_allocacmp_krow_V_1 <= ap_const_lv2_0;
        else 
            ap_sig_allocacmp_krow_V_1 <= krow_V_fu_82;
        end if; 
    end process;

    grp_fu_420_p0 <= grp_fu_420_p00(8 - 1 downto 0);
    grp_fu_420_p00 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(img_in_q0),16));
    icmp_ln1072_1_fu_244_p2 <= "1" when (ap_sig_allocacmp_kcol_V_load = ap_const_lv2_3) else "0";
    icmp_ln1072_fu_229_p2 <= "1" when (ap_sig_allocacmp_indvar_flatten_load = ap_const_lv4_9) else "0";
    image_1d_loc_fu_366_p2 <= std_logic_vector(unsigned(zext_ln70_7_fu_362_p1) + unsigned(select_ln27_2_fu_326_p3));
    img_in_address0 <= zext_ln587_1_fu_397_p1(6 - 1 downto 0);

    img_in_ce0_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter1, ap_block_pp0_stage0_11001)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            img_in_ce0 <= ap_const_logic_1;
        else 
            img_in_ce0 <= ap_const_logic_0;
        end if; 
    end process;

    select_ln1072_fu_334_p3 <= 
        add_ln885_fu_258_p2 when (icmp_ln1072_1_fu_244_p2(0) = '1') else 
        ap_sig_allocacmp_krow_V_1;
    select_ln27_1_fu_286_p3 <= 
        sub_ln70_2_fu_280_p2 when (icmp_ln1072_1_fu_244_p2(0) = '1') else 
        sub_ln70_fu_191_p2;
    select_ln27_2_fu_326_p3 <= 
        sub_ln70_3_fu_320_p2 when (icmp_ln1072_1_fu_244_p2(0) = '1') else 
        sub_ln70_1_fu_223_p2;
    select_ln27_fu_250_p3 <= 
        ap_const_lv2_0 when (icmp_ln1072_1_fu_244_p2(0) = '1') else 
        ap_sig_allocacmp_kcol_V_load;
    shl_ln70_1_fu_203_p3 <= (add_ln70_fu_197_p2 & ap_const_lv3_0);
    shl_ln70_1_mid1_fu_300_p3 <= (add_ln70_1_fu_294_p2 & ap_const_lv3_0);
    shl_ln70_2_fu_211_p3 <= (add_ln70_fu_197_p2 & ap_const_lv1_0);
    shl_ln70_2_mid1_fu_308_p3 <= (add_ln70_1_fu_294_p2 & ap_const_lv1_0);
    shl_ln70_mid1_fu_272_p3 <= (add_ln885_fu_258_p2 & ap_const_lv2_0);
    shl_ln_fu_183_p3 <= (ap_sig_allocacmp_krow_V_1 & ap_const_lv2_0);
    sub_ln70_1_fu_223_p2 <= std_logic_vector(unsigned(shl_ln70_1_fu_203_p3) - unsigned(zext_ln70_2_fu_219_p1));
    sub_ln70_2_fu_280_p2 <= std_logic_vector(unsigned(shl_ln70_mid1_fu_272_p3) - unsigned(zext_ln70_4_fu_268_p1));
    sub_ln70_3_fu_320_p2 <= std_logic_vector(unsigned(shl_ln70_1_mid1_fu_300_p3) - unsigned(zext_ln70_8_fu_316_p1));
    sub_ln70_fu_191_p2 <= std_logic_vector(unsigned(shl_ln_fu_183_p3) - unsigned(zext_ln70_1_fu_179_p1));
    weight_1d_loc_fu_350_p2 <= std_logic_vector(unsigned(zext_ln70_6_fu_346_p1) + unsigned(select_ln27_1_fu_286_p3));
    weights_address0 <= zext_ln587_fu_393_p1(4 - 1 downto 0);

    weights_ce0_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter1, ap_block_pp0_stage0_11001)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            weights_ce0 <= ap_const_logic_1;
        else 
            weights_ce0 <= ap_const_logic_0;
        end if; 
    end process;

    zext_ln23_cast_fu_145_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(zext_ln23),3));
    zext_ln27_cast_fu_141_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(zext_ln27),3));
    zext_ln587_1_fu_397_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(image_1d_loc_reg_467),64));
    zext_ln587_fu_393_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(weight_1d_loc_reg_462),64));
    zext_ln70_1_fu_179_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(ap_sig_allocacmp_krow_V_1),4));
    zext_ln70_2_fu_219_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(shl_ln70_2_fu_211_p3),6));
    zext_ln70_3_fu_264_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(add_ln885_fu_258_p2),3));
    zext_ln70_4_fu_268_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(add_ln885_fu_258_p2),4));
    zext_ln70_5_fu_342_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(select_ln27_fu_250_p3),3));
    zext_ln70_6_fu_346_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(select_ln27_fu_250_p3),4));
    zext_ln70_7_fu_362_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(add_ln70_2_fu_356_p2),6));
    zext_ln70_8_fu_316_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(shl_ln70_2_mid1_fu_308_p3),6));
    zext_ln70_fu_175_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(ap_sig_allocacmp_krow_V_1),3));
end behav;
